# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DGFB0nnBg5stp/8muy9jCgDkX8vD8c7tpz0BSpmyUK62WeyEsDdR+0LwiKZgCy1QBFMRHWFpSL+FUTAD31JOyh0tQnCgZMmMcqTRxCacnVKlhWvQs9rR4ZSDEUNuImE4Q+5CjSpkJbZUHydH+iQwbYS5vHIyqtABb/mGUlTJ1NVlGOaGh+VN/Y7kMo669ErBKJBPoiWKrc7nmMRjJIBuKcpjQJWSAtsIGCAnurM9h6CvinUpLZtVzgG96ocvC/EMPwVZWNOQgmXaengvCSCj/vxWroc3zeO70KBiK4sY3ffez+C7RrZBs0PK9L0jaIxUbrix/QNGYAanOYHZm530cguKQ8r1ARNdIS84/nzBowlC4/u8zUF08smpXCYqIRbI6mexHnkDYml7pASQAfUlAYnB8VVHgOCDJHVCnVO5o4kGzXohoAfue5V2HivKIOR3vESt6EmfKzOvyCWtV5dqS3QcrYqwffUiRcZjH0vDuD/9+XSdmBh6NeC65QQxW/GXfQLFfMx/GSNMjPW8GwCq1HJxp/vbkXAEWsK7Ayf3nIeAx4x2O6UcNRCmdj3kJqVj7NwX0Db2s5P5DBxnb21iztHw9vAgyf9x6QEltzTABoCmFrn7qvmG+9vBxZHOw+k1zJ9OBQmtFyf4kvVqG8+SN3uMXDSq9m8fo2ousR8FTj8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
